/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElContainer: typeof import('element-plus/es')['ElContainer']
    Foot: typeof import('./src/components/Layout/Foot/index.vue')['default']
    Head: typeof import('./src/components/Layout/Head/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Main: typeof import('./src/components/Layout/Main/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Layout/Sider/index.vue')['default']
  }
}
