/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminAside: typeof import('./components/Admin/Aside/src/AdminAside.vue')['default']
    AdminHead: typeof import('./components/Admin/Head/src/AdminHead.vue')['default']
    AsyncSlowEntry: typeof import('./components/AsyncSlowEntry.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Foot: typeof import('./components/Layout/Foot/index.vue')['default']
    Head: typeof import('./components/Layout/Head/index.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    Login: typeof import('./components/Login/src/Login.vue')['default']
    Main: typeof import('./components/Layout/Main/index.vue')['default']
    MBackTop: typeof import('./components/global/MBackTop/src/MBackTop.vue')['default']
    MBackToTop: typeof import('./components/global/MBackToTop/src/MBackToTop.vue')['default']
    MBadge: typeof import('./components/global/MBadge/src/MBadge.vue')['default']
    MDrop: typeof import('./components/global/MDrop/src/MDrop.vue')['default']
    MForm: typeof import('./components/global/MForm/src/MForm.vue')['default']
    MHero: typeof import('./components/global/MHero/src/MHero.vue')['default']
    Nav: typeof import('./components/Nav/src/Nav.vue')['default']
    NavDropMenu: typeof import('./components/Nav/src/NavDropMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search/src/Search.vue')['default']
    Sider: typeof import('./components/Layout/Sider/index.vue')['default']
    SvgCaptcha: typeof import('./components/SvgCaptcha/src/SvgCaptcha.vue')['default']
  }
}
