/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsyncSlowEntry: typeof import('./components/AsyncSlowEntry.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Foot: typeof import('./components/Layout/Foot/index.vue')['default']
    Head: typeof import('./components/Layout/Head/index.vue')['default']
    Hero: typeof import('./components/Layout/Hero/index.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    Login: typeof import('./components/Login/src/Login.vue')['default']
    Main: typeof import('./components/Layout/Main/index.vue')['default']
    Nav: typeof import('./components/Nav/src/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./components/Layout/Sider/index.vue')['default']
    SvgCaptcha: typeof import('./components/SvgCaptcha/src/SvgCaptcha.vue')['default']
    YForm: typeof import('./components/global/YForm/src/YForm.vue')['default']
  }
}
